--Q1. What is the total revenue generated by male vs. female customers?
-- group by gender -> purchase_amount
select sum(purchase_amount) as total_revenue , gender
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id
from customer
where discount_applied ='Yes'
and purchase_amount > (
			select avg(purchase_amount) 
			from customer
);


--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as avg_review_rate
from customer
group by item_purchased
order by avg_review_rate desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , avg(purchase_amount) as avg_purchase_amt
from customer
where shipping_type = 'Express' or shipping_type='Standard'
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased ,
	   round(
			100 * sum(case when discount_applied ='Yes' then 1 else 0 end) /count(*),2
	   )as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select count(*),
	case 
		when previous_purchases <=10 then 'New'
		when previous_purchases >10 and previous_purchases <=25 then 'Returning' 
		else 'Loyal' 
	end as customer_segment
from customer
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
select category , 
	   item_purchased , 
	   purchased_cnt
from (	select category , 
			   item_purchased , 
			   count(*) as purchased_cnt,
				dense_rank() over 
							(partition by category 
		 						order by count(*) desc
							) as rank_num
		from customer
		group by category, item_purchased
) as ranked_prod
where rank_num <=3
order by category, rank_num;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customer;
-- customer_id -> previous_purchase>5 && subscribe ? yes: no

select 	subscription_status,count(*) as customer_cnt
from customer
where previous_purchases > 5 
group by subscription_status;

--Q10. What is the revenue contribution of each age group?

select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group;


